name: pick_up_recipe
description: "Flutter coffee application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  build_runner: ^2.4.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  percent_indicator: ^4.2.3
  sliver_text: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
