name: pick_up_recipe
description: "Flutter coffee application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  build_runner: ^2.4.9
  camera: ^0.11.0+1
  encrypt_shared_preferences: ^0.8.2
#  encrypted_shared_preferences: ^3.0.1
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.4.3
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  go_router: ^14.6.2
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  sliver_text: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
