name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd pick_up_recipe
          flutter pub get

      - name: Run build_runner
        run: |
          cd pick_up_recipe
          dart run build_runner build --delete-conflicting-outputs

      - name: Verify formatting
        run: |
          cd pick_up_recipe
          dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: |
          cd pick_up_recipe
          flutter analyze

      - name: Run tests
        run: |
          cd pick_up_recipe
          flutter test
